name: Release latest binary on centos
on:
  pull_request:
    branches:
      - main
jobs:
  run:
    name: Upload
    runs-on: centos-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.4
        id: go

      - uses: actions/checkout@master
        with:
          # Must use at least depth 2!
          fetch-depth: 2
      - uses: actions/setup-python@v2
      - name: Configure awscli
        run: |
          pip3 install awscli
          printf "%s\n" ${{ secrets.AWS_ACCESS_KEY }} ${{ secrets.AWS_SECRET_KEY }} ${{ secrets.AWS_REGION }} "json" | aws configure
      - name: Build binary
        run: make build
      - name: Upload files
        run: |
          aws s3 cp bin/chaosd ${{ secrets.AWS_BUCKET_NAME }}/latest/chaosd_centos_test
