name: Release latest binary
on:
  push:
    branches:
      - main

jobs:
  run:
    name: Upload
    runs-on: ubuntu-latest
    # glibc version 2.17
    container: docker.io/centos:7.2.1511
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.2
        id: go

      - uses: actions/checkout@master
        with:
          # Must use at least depth 2!
          fetch-depth: 2

      - name: Setup python3
        run: |
          yum install -y python3
          alias python=python3

      - name: Configure awscli
        run: |
          pip3 install awscli
          printf "%s\n" ${{ secrets.AWS_ACCESS_KEY }} ${{ secrets.AWS_SECRET_KEY }} ${{ secrets.AWS_REGION }} "json" | aws configure

      - name: Prepare build environment
        run: |
          yum install -y gcc
          yum install -y make
          yum install -y binutils

      - name: Build binary
        run: make build

      - name: Upload files
        run: |
          aws s3 cp bin/chaosd ${{ secrets.AWS_BUCKET_NAME }}/latest/chaosd
